// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID              pgtype.UUID        `json:"id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	LocationName    pgtype.Text        `json:"location_name"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	CapacityMax     pgtype.Int4        `json:"capacity_max"`
	AccessTier      string             `json:"access_tier"`
	AutoAccept      bool               `json:"auto_accept"`
	Category        pgtype.Text        `json:"category"`
	InvitePolicy    string             `json:"invite_policy"`
	Discoverability string             `json:"discoverability"`
	CoverPhotoUrl   pgtype.Text        `json:"cover_photo_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type EventHost struct {
	EventID   pgtype.UUID        `json:"event_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	AddedBy   pgtype.UUID        `json:"added_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EventInvite struct {
	EventID   pgtype.UUID        `json:"event_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EventRsvp struct {
	EventID     pgtype.UUID        `json:"event_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Status      string             `json:"status"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
}

type Friendship struct {
	RequesterID pgtype.UUID        `json:"requester_id"`
	AddresseeID pgtype.UUID        `json:"addressee_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	AccessTier  string             `json:"access_tier"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type GroupInvite struct {
	GroupID   pgtype.UUID        `json:"group_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GroupMember struct {
	GroupID  pgtype.UUID        `json:"group_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     string             `json:"role"`
	Status   string             `json:"status"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
