// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :one
INSERT INTO group_members (group_id, user_id, role, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (group_id, user_id)
DO UPDATE SET role = EXCLUDED.role, status = EXCLUDED.status
RETURNING group_id, user_id, role, status, joined_at
`

type AddGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Role    string      `json:"role"`
	Status  string      `json:"status"`
}

// Owner is set once at group creation (see createGroupHandler); everyone
// who joins afterward defaults to 'member'. ON CONFLICT lets someone who
// left and rejoined get a fresh row instead of erroring on the PK.
func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, addGroupMember,
		arg.GroupID,
		arg.UserID,
		arg.Role,
		arg.Status,
	)
	var i GroupMember
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const countJoinedRSVPs = `-- name: CountJoinedRSVPs :one
SELECT COUNT(*) FROM event_rsvps
WHERE event_id = $1 AND status = 'joined'
`

func (q *Queries) CountJoinedRSVPs(ctx context.Context, eventID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countJoinedRSVPs, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    title, description, latitude, longitude, starts_at, created_by, access_tier,
    capacity_max, group_id, category, invite_policy, discoverability, cover_photo_url, auto_accept
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, group_id, created_by, title, description, location_name, latitude, longitude, starts_at, ends_at, capacity_max, access_tier, auto_accept, category, invite_policy, discoverability, cover_photo_url, created_at
`

type CreateEventParams struct {
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	AccessTier      string             `json:"access_tier"`
	CapacityMax     pgtype.Int4        `json:"capacity_max"`
	GroupID         pgtype.UUID        `json:"group_id"`
	Category        pgtype.Text        `json:"category"`
	InvitePolicy    string             `json:"invite_policy"`
	Discoverability string             `json:"discoverability"`
	CoverPhotoUrl   pgtype.Text        `json:"cover_photo_url"`
	AutoAccept      bool               `json:"auto_accept"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.Description,
		arg.Latitude,
		arg.Longitude,
		arg.StartsAt,
		arg.CreatedBy,
		arg.AccessTier,
		arg.CapacityMax,
		arg.GroupID,
		arg.Category,
		arg.InvitePolicy,
		arg.Discoverability,
		arg.CoverPhotoUrl,
		arg.AutoAccept,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.LocationName,
		&i.Latitude,
		&i.Longitude,
		&i.StartsAt,
		&i.EndsAt,
		&i.CapacityMax,
		&i.AccessTier,
		&i.AutoAccept,
		&i.Category,
		&i.InvitePolicy,
		&i.Discoverability,
		&i.CoverPhotoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createEventHost = `-- name: CreateEventHost :one
INSERT INTO event_hosts (event_id, user_id, added_by)
VALUES ($1, $2, $3)
ON CONFLICT (event_id, user_id) DO NOTHING
RETURNING event_id, user_id, added_by, created_at
`

type CreateEventHostParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  pgtype.UUID `json:"user_id"`
	AddedBy pgtype.UUID `json:"added_by"`
}

func (q *Queries) CreateEventHost(ctx context.Context, arg CreateEventHostParams) (EventHost, error) {
	row := q.db.QueryRow(ctx, createEventHost, arg.EventID, arg.UserID, arg.AddedBy)
	var i EventHost
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.AddedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createEventInvite = `-- name: CreateEventInvite :one
INSERT INTO event_invites (event_id, user_id, invited_by)
VALUES ($1, $2, $3)
ON CONFLICT (event_id, user_id) DO NOTHING
RETURNING event_id, user_id, invited_by, created_at
`

type CreateEventInviteParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	UserID    pgtype.UUID `json:"user_id"`
	InvitedBy pgtype.UUID `json:"invited_by"`
}

func (q *Queries) CreateEventInvite(ctx context.Context, arg CreateEventInviteParams) (EventInvite, error) {
	row := q.db.QueryRow(ctx, createEventInvite, arg.EventID, arg.UserID, arg.InvitedBy)
	var i EventInvite
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, description, created_by, access_tier)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, created_by, access_tier, created_at
`

type CreateGroupParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CreatedBy   pgtype.UUID `json:"created_by"`
	AccessTier  string      `json:"access_tier"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
		arg.AccessTier,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.AccessTier,
		&i.CreatedAt,
	)
	return i, err
}

const createGroupInvite = `-- name: CreateGroupInvite :one
INSERT INTO group_invites (group_id, user_id, invited_by)
VALUES ($1, $2, $3)
ON CONFLICT (group_id, user_id) DO NOTHING
RETURNING group_id, user_id, invited_by, created_at
`

type CreateGroupInviteParams struct {
	GroupID   pgtype.UUID `json:"group_id"`
	UserID    pgtype.UUID `json:"user_id"`
	InvitedBy pgtype.UUID `json:"invited_by"`
}

func (q *Queries) CreateGroupInvite(ctx context.Context, arg CreateGroupInviteParams) (GroupInvite, error) {
	row := q.db.QueryRow(ctx, createGroupInvite, arg.GroupID, arg.UserID, arg.InvitedBy)
	var i GroupInvite
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name)
VALUES ($1, $2)
RETURNING id, email, name, created_at
`

type CreateUserParams struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const deleteRSVP = `-- name: DeleteRSVP :exec
DELETE FROM event_rsvps
WHERE event_id = $1 AND user_id = $2
`

type DeleteRSVPParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteRSVP(ctx context.Context, arg DeleteRSVPParams) error {
	_, err := q.db.Exec(ctx, deleteRSVP, arg.EventID, arg.UserID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, group_id, created_by, title, description, location_name, latitude, longitude, starts_at, ends_at, capacity_max, access_tier, auto_accept, category, invite_policy, discoverability, cover_photo_url, created_at FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.LocationName,
		&i.Latitude,
		&i.Longitude,
		&i.StartsAt,
		&i.EndsAt,
		&i.CapacityMax,
		&i.AccessTier,
		&i.AutoAccept,
		&i.Category,
		&i.InvitePolicy,
		&i.Discoverability,
		&i.CoverPhotoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getEventForUpdate = `-- name: GetEventForUpdate :one
SELECT id, group_id, capacity_max, access_tier, auto_accept FROM events
WHERE id = $1
FOR UPDATE
`

type GetEventForUpdateRow struct {
	ID          pgtype.UUID `json:"id"`
	GroupID     pgtype.UUID `json:"group_id"`
	CapacityMax pgtype.Int4 `json:"capacity_max"`
	AccessTier  string      `json:"access_tier"`
	AutoAccept  bool        `json:"auto_accept"`
}

// FOR UPDATE locks this row until the enclosing transaction commits or
// rolls back. Any other transaction trying to lock the same row (via this
// same query) has to wait its turn — that's what makes capacity checks safe
// under concurrent requests.
func (q *Queries) GetEventForUpdate(ctx context.Context, id pgtype.UUID) (GetEventForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getEventForUpdate, id)
	var i GetEventForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CapacityMax,
		&i.AccessTier,
		&i.AutoAccept,
	)
	return i, err
}

const getEventHost = `-- name: GetEventHost :one
SELECT event_id, user_id, added_by, created_at FROM event_hosts WHERE event_id = $1 AND user_id = $2
`

type GetEventHostParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetEventHost(ctx context.Context, arg GetEventHostParams) (EventHost, error) {
	row := q.db.QueryRow(ctx, getEventHost, arg.EventID, arg.UserID)
	var i EventHost
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.AddedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getEventInvite = `-- name: GetEventInvite :one
SELECT event_id, user_id, invited_by, created_at FROM event_invites WHERE event_id = $1 AND user_id = $2
`

type GetEventInviteParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetEventInvite(ctx context.Context, arg GetEventInviteParams) (EventInvite, error) {
	row := q.db.QueryRow(ctx, getEventInvite, arg.EventID, arg.UserID)
	var i EventInvite
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getEventOwner = `-- name: GetEventOwner :one
SELECT created_by FROM events WHERE id = $1
`

func (q *Queries) GetEventOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getEventOwner, id)
	var created_by pgtype.UUID
	err := row.Scan(&created_by)
	return created_by, err
}

const getFriendship = `-- name: GetFriendship :one
SELECT requester_id, addressee_id, status, created_at FROM friendships
WHERE (requester_id = $1 AND addressee_id = $2)
   OR (requester_id = $2 AND addressee_id = $1)
`

type GetFriendshipParams struct {
	RequesterID pgtype.UUID `json:"requester_id"`
	AddresseeID pgtype.UUID `json:"addressee_id"`
}

func (q *Queries) GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendship, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, description, created_by, access_tier, created_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.AccessTier,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupInvite = `-- name: GetGroupInvite :one
SELECT group_id, user_id, invited_by, created_at FROM group_invites WHERE group_id = $1 AND user_id = $2
`

type GetGroupInviteParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetGroupInvite(ctx context.Context, arg GetGroupInviteParams) (GroupInvite, error) {
	row := q.db.QueryRow(ctx, getGroupInvite, arg.GroupID, arg.UserID)
	var i GroupInvite
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT group_id, user_id, role, status, joined_at FROM group_members WHERE group_id = $1 AND user_id = $2
`

type GetGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const getGroupOwner = `-- name: GetGroupOwner :one
SELECT created_by FROM groups WHERE id = $1
`

func (q *Queries) GetGroupOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getGroupOwner, id)
	var created_by pgtype.UUID
	err := row.Scan(&created_by)
	return created_by, err
}

const getOldestWaitlisted = `-- name: GetOldestWaitlisted :one
SELECT event_id, user_id, status, requested_at FROM event_rsvps
WHERE event_id = $1 AND status = 'waitlisted'
ORDER BY requested_at ASC
LIMIT 1
`

// Used after someone leaves, to find who should be promoted off the waitlist.
func (q *Queries) GetOldestWaitlisted(ctx context.Context, eventID pgtype.UUID) (EventRsvp, error) {
	row := q.db.QueryRow(ctx, getOldestWaitlisted, eventID)
	var i EventRsvp
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.RequestedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, created_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, email, name, created_at FROM users
WHERE name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listEventHosts = `-- name: ListEventHosts :many
SELECT event_id, user_id, added_by, created_at FROM event_hosts WHERE event_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListEventHosts(ctx context.Context, eventID pgtype.UUID) ([]EventHost, error) {
	rows, err := q.db.Query(ctx, listEventHosts, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventHost
	for rows.Next() {
		var i EventHost
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.AddedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventInvites = `-- name: ListEventInvites :many
SELECT event_id, user_id, invited_by, created_at FROM event_invites WHERE event_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListEventInvites(ctx context.Context, eventID pgtype.UUID) ([]EventInvite, error) {
	rows, err := q.db.Query(ctx, listEventInvites, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventInvite
	for rows.Next() {
		var i EventInvite
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.InvitedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, group_id, created_by, title, description, location_name, latitude, longitude, starts_at, ends_at, capacity_max, access_tier, auto_accept, category, invite_policy, discoverability, cover_photo_url, created_at FROM events
ORDER BY starts_at ASC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.LocationName,
			&i.Latitude,
			&i.Longitude,
			&i.StartsAt,
			&i.EndsAt,
			&i.CapacityMax,
			&i.AccessTier,
			&i.AutoAccept,
			&i.Category,
			&i.InvitePolicy,
			&i.Discoverability,
			&i.CoverPhotoUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForGroup = `-- name: ListEventsForGroup :many
SELECT id, group_id, created_by, title, description, location_name, latitude, longitude, starts_at, ends_at, capacity_max, access_tier, auto_accept, category, invite_policy, discoverability, cover_photo_url, created_at FROM events WHERE group_id = $1 ORDER BY starts_at ASC
`

func (q *Queries) ListEventsForGroup(ctx context.Context, groupID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.LocationName,
			&i.Latitude,
			&i.Longitude,
			&i.StartsAt,
			&i.EndsAt,
			&i.CapacityMax,
			&i.AccessTier,
			&i.AutoAccept,
			&i.Category,
			&i.InvitePolicy,
			&i.Discoverability,
			&i.CoverPhotoUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriends = `-- name: ListFriends :many
SELECT u.id, u.email, u.name, u.created_at FROM users u
JOIN friendships f ON (
    (f.requester_id = $1 AND f.addressee_id = u.id) OR
    (f.addressee_id = $1 AND f.requester_id = u.id)
)
WHERE f.status = 'accepted'
ORDER BY u.name ASC
`

// A friendship is "real" once accepted, and can be stored in either
// direction, so this checks both and returns whichever side ISN'T $1.
func (q *Queries) ListFriends(ctx context.Context, requesterID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listFriends, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupInvites = `-- name: ListGroupInvites :many
SELECT group_id, user_id, invited_by, created_at FROM group_invites WHERE group_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListGroupInvites(ctx context.Context, groupID pgtype.UUID) ([]GroupInvite, error) {
	rows, err := q.db.Query(ctx, listGroupInvites, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupInvite
	for rows.Next() {
		var i GroupInvite
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.InvitedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT group_id, user_id, role, status, joined_at FROM group_members WHERE group_id = $1 ORDER BY joined_at ASC
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GroupMember, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, description, created_by, access_tier, created_at FROM groups ORDER BY created_at DESC
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.AccessTier,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForUser = `-- name: ListGroupsForUser :many
SELECT g.id, g.name, g.description, g.created_by, g.access_tier, g.created_at FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1
ORDER BY g.created_at DESC
`

func (q *Queries) ListGroupsForUser(ctx context.Context, userID pgtype.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.AccessTier,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostedEventsForUser = `-- name: ListHostedEventsForUser :many
SELECT DISTINCT e.id, e.group_id, e.created_by, e.title, e.description, e.location_name, e.latitude, e.longitude, e.starts_at, e.ends_at, e.capacity_max, e.access_tier, e.auto_accept, e.category, e.invite_policy, e.discoverability, e.cover_photo_url, e.created_at FROM events e
LEFT JOIN event_hosts eh ON eh.event_id = e.id
WHERE e.created_by = $1 OR eh.user_id = $1
ORDER BY e.starts_at ASC
`

// "My events" — anything the user created OR co-hosts.
func (q *Queries) ListHostedEventsForUser(ctx context.Context, createdBy pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listHostedEventsForUser, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.LocationName,
			&i.Latitude,
			&i.Longitude,
			&i.StartsAt,
			&i.EndsAt,
			&i.CapacityMax,
			&i.AccessTier,
			&i.AutoAccept,
			&i.Category,
			&i.InvitePolicy,
			&i.Discoverability,
			&i.CoverPhotoUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitedEventsForUser = `-- name: ListInvitedEventsForUser :many
SELECT e.id, e.group_id, e.created_by, e.title, e.description, e.location_name, e.latitude, e.longitude, e.starts_at, e.ends_at, e.capacity_max, e.access_tier, e.auto_accept, e.category, e.invite_policy, e.discoverability, e.cover_photo_url, e.created_at FROM events e
JOIN event_invites ei ON ei.event_id = e.id
WHERE ei.user_id = $1
ORDER BY e.starts_at ASC
`

// Events this user has been invited to, regardless of whether they've
// responded yet — this is the "pending invites" view that never existed
// before (previously invites only worked if you already had the link).
func (q *Queries) ListInvitedEventsForUser(ctx context.Context, userID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listInvitedEventsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.LocationName,
			&i.Latitude,
			&i.Longitude,
			&i.StartsAt,
			&i.EndsAt,
			&i.CapacityMax,
			&i.AccessTier,
			&i.AutoAccept,
			&i.Category,
			&i.InvitePolicy,
			&i.Discoverability,
			&i.CoverPhotoUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingFriendRequests = `-- name: ListPendingFriendRequests :many
SELECT f.requester_id, u.name, u.email, f.created_at
FROM friendships f
JOIN users u ON u.id = f.requester_id
WHERE f.addressee_id = $1 AND f.status = 'pending'
ORDER BY f.created_at ASC
`

type ListPendingFriendRequestsRow struct {
	RequesterID pgtype.UUID        `json:"requester_id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Requests THIS user has received and hasn't responded to yet.
func (q *Queries) ListPendingFriendRequests(ctx context.Context, addresseeID pgtype.UUID) ([]ListPendingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listPendingFriendRequests, addresseeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingFriendRequestsRow
	for rows.Next() {
		var i ListPendingFriendRequestsRow
		if err := rows.Scan(
			&i.RequesterID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingGroupMembers = `-- name: ListPendingGroupMembers :many
SELECT group_id, user_id, role, status, joined_at FROM group_members WHERE group_id = $1 AND status = 'pending' ORDER BY joined_at ASC
`

func (q *Queries) ListPendingGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GroupMember, error) {
	rows, err := q.db.Query(ctx, listPendingGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRSVPdEventsForUser = `-- name: ListRSVPdEventsForUser :many
SELECT e.id, e.group_id, e.created_by, e.title, e.description, e.location_name, e.latitude, e.longitude, e.starts_at, e.ends_at, e.capacity_max, e.access_tier, e.auto_accept, e.category, e.invite_policy, e.discoverability, e.cover_photo_url, e.created_at, r.status AS rsvp_status FROM events e
JOIN event_rsvps r ON r.event_id = e.id
WHERE r.user_id = $1
ORDER BY e.starts_at ASC
`

type ListRSVPdEventsForUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	LocationName    pgtype.Text        `json:"location_name"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	CapacityMax     pgtype.Int4        `json:"capacity_max"`
	AccessTier      string             `json:"access_tier"`
	AutoAccept      bool               `json:"auto_accept"`
	Category        pgtype.Text        `json:"category"`
	InvitePolicy    string             `json:"invite_policy"`
	Discoverability string             `json:"discoverability"`
	CoverPhotoUrl   pgtype.Text        `json:"cover_photo_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	RsvpStatus      string             `json:"rsvp_status"`
}

// "Going" — every event this user has any RSVP row for, plus that RSVP's
// status, so the frontend can distinguish joined/maybe/pending/waitlisted.
func (q *Queries) ListRSVPdEventsForUser(ctx context.Context, userID pgtype.UUID) ([]ListRSVPdEventsForUserRow, error) {
	rows, err := q.db.Query(ctx, listRSVPdEventsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRSVPdEventsForUserRow
	for rows.Next() {
		var i ListRSVPdEventsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.LocationName,
			&i.Latitude,
			&i.Longitude,
			&i.StartsAt,
			&i.EndsAt,
			&i.CapacityMax,
			&i.AccessTier,
			&i.AutoAccept,
			&i.Category,
			&i.InvitePolicy,
			&i.Discoverability,
			&i.CoverPhotoUrl,
			&i.CreatedAt,
			&i.RsvpStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRSVPsForEvent = `-- name: ListRSVPsForEvent :many
SELECT event_id, user_id, status, requested_at FROM event_rsvps WHERE event_id = $1 ORDER BY requested_at ASC
`

func (q *Queries) ListRSVPsForEvent(ctx context.Context, eventID pgtype.UUID) ([]EventRsvp, error) {
	rows, err := q.db.Query(ctx, listRSVPsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventRsvp
	for rows.Next() {
		var i EventRsvp
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.Status,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentFriendRequests = `-- name: ListSentFriendRequests :many
SELECT f.addressee_id, u.name, u.email, f.created_at
FROM friendships f
JOIN users u ON u.id = f.addressee_id
WHERE f.requester_id = $1 AND f.status = 'pending'
ORDER BY f.created_at ASC
`

type ListSentFriendRequestsRow struct {
	AddresseeID pgtype.UUID        `json:"addressee_id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Requests THIS user has sent that the other person hasn't responded to
// yet — the mirror image of ListPendingFriendRequests, used to show
// "Request sent" instead of "Add friend" on the Users page.
func (q *Queries) ListSentFriendRequests(ctx context.Context, requesterID pgtype.UUID) ([]ListSentFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listSentFriendRequests, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSentFriendRequestsRow
	for rows.Next() {
		var i ListSentFriendRequestsRow
		if err := rows.Scan(
			&i.AddresseeID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, created_at FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeEventHost = `-- name: RemoveEventHost :exec
DELETE FROM event_hosts WHERE event_id = $1 AND user_id = $2
`

type RemoveEventHostParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveEventHost(ctx context.Context, arg RemoveEventHostParams) error {
	_, err := q.db.Exec(ctx, removeEventHost, arg.EventID, arg.UserID)
	return err
}

const removeFriendship = `-- name: RemoveFriendship :exec
DELETE FROM friendships
WHERE (requester_id = $1 AND addressee_id = $2)
   OR (requester_id = $2 AND addressee_id = $1)
`

type RemoveFriendshipParams struct {
	RequesterID pgtype.UUID `json:"requester_id"`
	AddresseeID pgtype.UUID `json:"addressee_id"`
}

// Direction-agnostic: removes the row regardless of who originally sent
// the request, since "unfriending" should work either way.
func (q *Queries) RemoveFriendship(ctx context.Context, arg RemoveFriendshipParams) error {
	_, err := q.db.Exec(ctx, removeFriendship, arg.RequesterID, arg.AddresseeID)
	return err
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const respondToFriendRequest = `-- name: RespondToFriendRequest :one
UPDATE friendships
SET status = $3
WHERE requester_id = $1 AND addressee_id = $2
RETURNING requester_id, addressee_id, status, created_at
`

type RespondToFriendRequestParams struct {
	RequesterID pgtype.UUID `json:"requester_id"`
	AddresseeID pgtype.UUID `json:"addressee_id"`
	Status      string      `json:"status"`
}

// Note the direction: only the addressee (the person who received the
// request) should be able to accept/decline it — enforced in Go, not SQL.
func (q *Queries) RespondToFriendRequest(ctx context.Context, arg RespondToFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, respondToFriendRequest, arg.RequesterID, arg.AddresseeID, arg.Status)
	var i Friendship
	err := row.Scan(
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const sendFriendRequest = `-- name: SendFriendRequest :one
INSERT INTO friendships (requester_id, addressee_id, status)
VALUES ($1, $2, 'pending')
ON CONFLICT (requester_id, addressee_id)
DO UPDATE SET status = 'pending', created_at = now()
RETURNING requester_id, addressee_id, status, created_at
`

type SendFriendRequestParams struct {
	RequesterID pgtype.UUID `json:"requester_id"`
	AddresseeID pgtype.UUID `json:"addressee_id"`
}

// ON CONFLICT lets someone re-send after a decline, refreshing it back to
// pending instead of erroring on the (requester_id, addressee_id) PK.
func (q *Queries) SendFriendRequest(ctx context.Context, arg SendFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, sendFriendRequest, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $2, description = $3, latitude = $4, longitude = $5, starts_at = $6,
    access_tier = $7, capacity_max = $8, category = $9, invite_policy = $10,
    discoverability = $11, cover_photo_url = $12, auto_accept = $13
WHERE id = $1
RETURNING id, group_id, created_by, title, description, location_name, latitude, longitude, starts_at, ends_at, capacity_max, access_tier, auto_accept, category, invite_policy, discoverability, cover_photo_url, created_at
`

type UpdateEventParams struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	AccessTier      string             `json:"access_tier"`
	CapacityMax     pgtype.Int4        `json:"capacity_max"`
	Category        pgtype.Text        `json:"category"`
	InvitePolicy    string             `json:"invite_policy"`
	Discoverability string             `json:"discoverability"`
	CoverPhotoUrl   pgtype.Text        `json:"cover_photo_url"`
	AutoAccept      bool               `json:"auto_accept"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Latitude,
		arg.Longitude,
		arg.StartsAt,
		arg.AccessTier,
		arg.CapacityMax,
		arg.Category,
		arg.InvitePolicy,
		arg.Discoverability,
		arg.CoverPhotoUrl,
		arg.AutoAccept,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.LocationName,
		&i.Latitude,
		&i.Longitude,
		&i.StartsAt,
		&i.EndsAt,
		&i.CapacityMax,
		&i.AccessTier,
		&i.AutoAccept,
		&i.Category,
		&i.InvitePolicy,
		&i.Discoverability,
		&i.CoverPhotoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updateGroupMemberStatus = `-- name: UpdateGroupMemberStatus :one
UPDATE group_members
SET status = $3
WHERE group_id = $1 AND user_id = $2
RETURNING group_id, user_id, role, status, joined_at
`

type UpdateGroupMemberStatusParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Status  string      `json:"status"`
}

// Used to promote a 'pending' request-tier member to 'active' (or decline
// by just removing the row via RemoveGroupMember instead).
func (q *Queries) UpdateGroupMemberStatus(ctx context.Context, arg UpdateGroupMemberStatusParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, updateGroupMemberStatus, arg.GroupID, arg.UserID, arg.Status)
	var i GroupMember
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const upsertRSVP = `-- name: UpsertRSVP :one
INSERT INTO event_rsvps (event_id, user_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (event_id, user_id)
DO UPDATE SET status = EXCLUDED.status, requested_at = now()
RETURNING event_id, user_id, status, requested_at
`

type UpsertRSVPParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Status  string      `json:"status"`
}

// ON CONFLICT handles a user re-joining/re-leaving an event they already
// have an RSVP row for, updating their existing row instead of erroring
// on the (event_id, user_id) primary key collision.
func (q *Queries) UpsertRSVP(ctx context.Context, arg UpsertRSVPParams) (EventRsvp, error) {
	row := q.db.QueryRow(ctx, upsertRSVP, arg.EventID, arg.UserID, arg.Status)
	var i EventRsvp
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.RequestedAt,
	)
	return i, err
}
